sudo: required
services:
  - docker

before_install:
  - docker build -t zavanton/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zavanton/react-test npm run test

after_success:
  - docker build -t zavanton/multi-client ./client
  - docker build -t zavanton/multi-nginx ./nginx
  - docker build -t zavanton/multi-server ./server
  - docker build -t zavanton/multi-worker ./worker
